# Generated by Django 4.2.5 on 2026-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_merge_20231007_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
