# Generated by Django 4.2.5 on 2026-05-24 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0013_emailverificationcode_bookingdate_booking_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('promo_code', models.CharField(db_index=True, max_length=64)),
                ('promo_title', models.CharField(blank=True, default='', max_length=255)),
                ('discount_label', models.CharField(blank=True, default='', max_length=32)),
                ('event_type', models.CharField(choices=[('copy', 'Копирование промокода'), ('apply', 'Применение акции'), ('details', 'Открытие подробностей')], db_index=True, max_length=32)),
                ('page', models.CharField(blank=True, default='promotions', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
