# Generated by Django 4.2.5 on 2026-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_promotionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxe',
            name='persons',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='luxeplus',
            name='persons',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='luxepremium',
            name='persons',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='standard',
            name='persons',
            field=models.IntegerField(default=2),
        ),
    ]
