# Generated by Django 4.2.5 on 2026-05-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0015_alter_luxe_persons_alter_luxeplus_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_records', to='hotel.room'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='booked',
            field=models.ManyToManyField(blank=True, related_name='legacy_booked_rooms', to='hotel.bookingdate'),
        ),
    ]
